Added loop support
common-workflow-language/cwl-v1.3 pull request #5
Opened 2022-12-24 16:11 UTC by GlassOfWhiskey

This commit adds the previous `Loop` requirement extension directly into the CWL v1.3 spec.

2022-12-25 17:38 UTC, GlassOfWhiskey commented
The important question here is: do we still need `loopSource` or we can directly use the `source` field here?
I remember the problem was that the `source` field requires a `step_name/output_name` format for the argument, while the `loopSource` here requires just the `output_name`, as the `step_name` is always the current one.

I think that we can proceed in two ways: either modify the `schema_salad` to handle both behaviors, or keep the `loopSource` specific definition.

2022-12-26 10:29 UTC, mr-c requested changes
Needs loop conformance tests, and needs all the tests to use `cwlVersion: v1.3.0-dev1` everywhere except for the mixed versions tests which should be adapted with care.

For testing purposes you could also adjust the CI to use cwltool from your PR. We can revert that bit once there is a cwltool release with `v1.3.0-dev1` support.

2022-12-26 10:46 UTC, mr-c commented on Workflow.yml
> +        refScope: 1
Hmmm.. `source` has `refScope: 2`

You could try setting `name: source` and ` "_id": "cwl:source"` and see what happens with
1.  `schema-salad-tool --codegen python` and the new schema (and if that works, try using the generated code to parse a CWL `v1.3.0-dev1` multi-step workflow with a `loop`)
2. `schema-salad-tool` in its default verification mode with the new schema and the same test documents from above
3. If both of those work (hurray!) then also test cwltool using the updated schema to run the test workflow from above

If that doesn't work then we would have to enhance schema-salad to allow `refScope` to not be the same for all instantiations of a term.

https://github.com/common-workflow-language/cwl-v1.3/blob/b84ec22210d53dc1d7190958bfe120da058bb690/Workflow.yml#L260

2022-12-26 17:18 UTC, GlassOfWhiskey commented on Workflow.yml
> +        refScope: 1
Putting `refScope: 1` breaks the codegen logic, as it introduces a conflict on the `source` predicate

```
Traceback (most recent call last):
  File "/home/glassofwhiskey/Projects/cwl/schema_salad/venv/bin/schema-salad-tool", line 8, in <module>
    sys.exit(main())
  File "/home/glassofwhiskey/Projects/cwl/schema_salad/venv/lib/python3.10/site-packages/schema_salad/main.py", line 317, in main
    (schema_ctx, rdfs) = jsonld_context.salad_to_jsonld_context(schema_doc, metactx)
  File "/home/glassofwhiskey/Projects/cwl/schema_salad/venv/lib/python3.10/site-packages/schema_salad/jsonld_context.py", line 220, in salad_to_jsonld_context
    process_type(t, g, context, defaultBase, namespaces, defaultPrefix)
  File "/home/glassofwhiskey/Projects/cwl/schema_salad/venv/lib/python3.10/site-packages/schema_salad/jsonld_context.py", line 142, in process_type
    v = pred(
  File "/home/glassofwhiskey/Projects/cwl/schema_salad/venv/lib/python3.10/site-packages/schema_salad/jsonld_context.py", line 80, in pred
    raise SchemaException(
schema_salad.exceptions.SchemaException: Predicate collision on source, '{'@id': 'https://w3id.org/cwl/cwl#source', '@type': '@id', 'refScope': 2}' != '{'@id': 'https://w3id.org/cwl/cwl#source', '@type': '@id', 'refScope': 1}'
```

I think either Schema SALAD needs a fix, or we must return to the `loopSource` name.

2022-12-28 20:55 UTC, GlassOfWhiskey commented
Putting this PR in Draft state, as it depends on [this one](#6).

2023-01-03 15:12 UTC, tetron commented on Workflow.yml
> +        refScope: 1
If I recall correctly this is the same reason for the split between `source` and `outputSource`.

The reasoning is that it allows for individual fields to be processed without knowing the context, the field name always means exactly one thing (including what refScope to use).

So yes, you either need to change how Schema salad works, or use `loopSource`.

2023-01-03 15:23 UTC, GlassOfWhiskey commented on Workflow.yml
> +        refScope: 1
I was thinking about using `outputSouce` also here. At the end of the day, it maps an output field, so `outputSource` fits well, and it has the required `refScope` value

2023-01-03 15:23 UTC, GlassOfWhiskey commented on Workflow.yml
> +        refScope: 1
This is why I put this PR in draft status to wait for #6

2023-01-03 15:34 UTC, tetron commented on Workflow.yml
> +        refScope: 1
Yes, if `outputSource` works here it would use that, it's conceptually consistent and avoids introducing a new field.

2023-01-03 17:38 UTC, mr-c requested changes
Needs a changelog entry and ideally some tests that don't use `InlineJavascriptRequirement`

2023-01-04 16:57 UTC, mr-c commented on tests/loop/all-output-loop-no-iteration.cwl
> -requirements:
I think line 14 (12) still needs `InlineJavascriptRequirement
> ` when: $(inputs.i1 < 1)`

2023-02-13 08:57 UTC, mr-c commented on CODE_OF_CONDUCT.md
> +you is on the team, they will recurse themselves from handling your incident. We
```suggestion
you is on the team, they will recuse themselves from handling your incident. We
```

https://en.wiktionary.org/wiki/recuse#English :-)

2024-05-16 14:03 UTC, mr-c commented
> Needs a changelog entry 

This is still true

2024-05-16 14:54 UTC, tetron requested changes

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
> +        `source` field, or the value produced by the `source` is `null`.  The
Should be `outputSource` instead of `source`

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
> +    Combining the two in the same step will produce an error.
rephrase: "It is a fatal error for both `scatter` and `loop` to appear in the same workflow step."

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
>  - name: WorkflowStep
As discussed, WorkflowStep should become AbstractWorkflowStep, and have three subtypes: "ScatterWorkflowStep", "LoopWorkflowStep" and "WorkflowStep" (for steps that do not scatter or loop).

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
>  - name: WorkflowStep
This will also pull the documentation of scatter and loop apart into separate sections.

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
> +        Required if `loop` is defined.
As discussed, instead of being required, this could default to "last" when not specified, agreed this is the behavior most likely to be expected by the user.

2024-05-16 14:54 UTC, tetron commented on tests/loop/invalid-multi-source-loop-no-requirement.cwl
> +    outputSource: [loop/osmall, loop/obig]
As discussed, would like to see a test that takes two values in output source but does not use pickValue, but uses valueFrom and $(self[0])

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
> +    When a `loop` field is present, the `when` field is mandatory. It is
I think we can use type narrowing to enforce this, the abstract base can have an optional `when` but the LoopWorkflowStep should re-define `when` to be required.

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
> +    Combining the two in the same step will produce an error.
As discussed, we can prevent this by refactoring the schema into separate LoopWorkflowStep and ScatterWorkflowStep

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
> +    and the step outputs are propagated to the subsequent workflow steps.
What happens if `when` is false before the first iteration?  (Probably it produces null on all outputs, but it needs to say so and there should be a test).

2024-05-16 14:54 UTC, tetron commented on Workflow.yml
> +      * **all** specifies that a single ordered array with all output values
What ordering?  (I assume the order that iterations happened but it should say so).

2024-05-17 09:33 UTC, tetron requested changes
Need a note about Loops in the changelog, also a mention that WorkflowStep has been split.

2024-05-17 09:33 UTC, tetron commented on Workflow.yml
> +  symbols:
Could we expand the names to `last_iteration_output` and `all_iteration_outputs`

2024-05-17 09:33 UTC, tetron commented on Workflow.yml
> +        is set to `last`, and an empty array if the `outputMehtod` is set to `all`.
`outputMehtod` is misspelled

2024-05-17 09:33 UTC, tetron commented on Workflow.yml
> +          items: [LoopWorkflowStep, ScatterWorkflowStep, WorkflowStep]
I believe if you just put "AbstractWorkflowStep" schema-salad will do the right thing.

2024-05-17 09:33 UTC, tetron commented on json-schema/cwl.yaml
> +      (see also: https://www.commonwl.org/v1.2/Workflow.html#ScatterWorkflowStep).
has the wrong version in the link

2024-05-17 11:26 UTC, GlassOfWhiskey commented on json-schema/cwl.yaml
> +      (see also: https://www.commonwl.org/v1.2/Workflow.html#ScatterWorkflowStep).
The json schema file is all wrong. Ao I revert the modification because I really hope there is a way to generate it automatically

2024-05-22 05:36 UTC, mr-c commented
@tom-tan We could make it optional but without needing a `LoopRequirement`, like conditionals are in CWL v1.2: https://www.commonwl.org/v1.2/Workflow.html#Conditional_execution_(Optional)

2024-07-18 14:07 UTC, tetron commented
My comment about "Could we expand the names to last_iteration_output and all_iteration_outputs" still applies, the rest looks good.

2024-07-18 20:34 UTC, mr-c commented on Workflow.yml
> +  symbols:
Maybe `outputMethod: last_iteration` and `outputMethod: all_iterations`?

2024-07-18 20:34 UTC, mr-c commented on Workflow.yml
> +  doc: The loop output method, as described in [workflow step loop](#LoopWorkflowStep).
and also described here :-)

2024-07-19 13:04 UTC, mr-c commented
There was an error in how we were running the self-check (are all the CWL documents used in the conformance tests valid at the schema level) which I fixed in #46 and rebased into here

`tests/loop/invalid-no-when.cwl` is invalid at the CWL schema level on purpose, which causes that check to fail. I'm not against having it in the conformance tests, but we need a way to easily mark it so we don't do the schema validation on it. 

1. Filename pattern; Alas `invalid` is also used in other conformance tests that are schema-salad compliant. Either we rename those files or find another word to stick in the CWL document filename
2. put schema-breaking tests in `tests/invalid` folder or similar

2024-09-16 19:30 UTC, GlassOfWhiskey commented
I think the best idea would be to simply remove the test, as we can easily rely on SchemaSalad validation to assess this behaviour, without the need for a specific test

2024-09-18 10:07 UTC, GlassOfWhiskey commented on Workflow.yml
> +  doc: The loop output method, as described in [workflow step loop](#LoopWorkflowStep).
This format is compliant to the `scatterMetod` field documented just above

2024-10-07 15:55 UTC, mr-c commented on .github/workflows/cwltool.yml
> +        run: pip install "cwltest>=2.3" pytest-xdist "cwltool>=3.1.20240909164951"
```suggestion
        run: pip install "cwltest>=2.3" pytest-xdist "cwltool>=3.1.20241007082533"
```

2024-10-07 15:57 UTC, mr-c requested changes
Please add a changelog, otherwise I approve!

2024-10-07 16:35 UTC, merged